version: '3.4'

services:
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"