name: Backend CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore  
    - name: Build
      run: dotnet build ./backend/Fyley.sln --configuration Release --no-restore 
    - name: Test
      run: dotnet test ./backend/Fyley.sln --no-restore --verbosity normal --filter FullyQualifiedName!~IntegrationTests